-- Tabela NCM - 3º nível
SELECT  A.TUK,
        A.IT_NU_NCM AS NCM,
        B.IT_NU_CLASSIFICACAO AS "CO-SEFIN",
        A.IT_CO_PRODUTO_ST AS "REGUL.-ST",
        A.IT_CO_PRODUTO_ISENTO AS "REGUL.-ISENTO",
        A.IT_IN_INSUMO AS "INSUMO RURAL",
        A.IT_CO_PRODUTO_INSUMO AS "COD.INSUMO",
        A.IT_IN_PREVALECE_ABCFARMA AS "PREVALECE S/ABCFARMA?",
        A.IT_NO_NCM AS DESCRICAO
FROM SITAFE.SITAFE_NCM A
LEFT OUTER JOIN SITAFE.SITAFE_NCM_GR_CLASSIF_PRODUTO B ON A.TUK = B.TUK
WHERE   IT_IN_STATUS_NCM <> 'C'
ORDER BY A.IT_NU_NCM